### ISSUE TITLE
Question about API key

### ISSUE THREAD

**Issue by dooniem** [osohotwateriot/osoenergy_community#2]
Is it right to assume the user will have to manually enter a new API key before it expires, or have you been able to renew it automatically?

**Comment by osohotwateriot** [comment]
Currently there is no mechanism to automatically renew the API key. What you say is correct - you would have to renew it manually and reconfigure the integration. The maximum expiration of the key is 1 year.

**Comment by dooniem** [comment]
Thanks for replying. I was mostly curious since I tried developing an integration for Homey Pro myself, and chose to start the development with tackling the auto-renewal of API-key. Since I couldn't do it I gave up on the whole project 😅    
Maybe that sounds a bit stupid, but forgetting to renew the API key once is enough to turn the whole family against you.

I guess you can close the issue if you like, or I / we can rename it if you think this could be an issue to be solved in the future.

**Comment by osohotwateriot** [comment]
For now an option to extend the validity period of the existing API key is added in the user portal in order to reuse the existing key without the need to update it in external systems like Home Assistant.
There is no decision to have an automatic renewal since it poses a security issue if stolen by someone else.
